apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-pp
data:
  default.conf: |
    server {
      listen 80 proxy_protocol;
      listen 443 ssl proxy_protocol;
      server_name  _;
      ssl_certificate certs/https.cert;
      ssl_certificate_key certs/https.key;
      ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
      ssl_ciphers  HIGH:!aNULL:!MD5;
      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
